m1=input("enter marks")
m2=input("enter marks")
m3=input("enter marks")
m4=input("enter marks")
m5=input("enter marks")
m6=input("enter marks")
m1=int(m1)
m2=int(m2)
m3=int(m3)
m4=int(m4)
m5=int(m5)
m6=int(m6)
marks=[m1,m2,m3,m4,m5,m6]
marks.sort()
print(marks)