a1=input("enter a number")
a2=input("enter a number")
a3=input("enter a number")
a4=input("enter a number")
a5=input("enter a number")
a6=input("enter a number")
a7=input("enter a number")
a8=input("enter a number")
a1=int(a1)
a2=int(a2)
a3=int(a3)
a4=int(a4)
a5=int(a5)
a6=int(a6)
a7=int(a7)
a8=int(a8)
s={a1,a2,a3,a4,a5,a6,a7,a8}
print(type(s))
print(s)